### ISSUE TITLE
SFTP not working correctly for some

### ISSUE THREAD

**Issue by t0phr** [afollestad/cabinet-issue-tracker#119]
On earlier versions SFTP worked fast and reliably. But since a few updates opening a folder on a SFTP share mostly shows "Error". It does not crash, the folder is just not displayed. Moving back to the parent folder afterwards works sometimes, but often also ends up showing "Error".
BUT: switching to another app and back while the SFTP connection is open fixes the issue. After a switch cycle I can browse every folder correctly.
EDIT: Switch cycle workaround does not work always. But it improves chances somewhat.

Nevertheless great app, great UI. And most important, a very fair pricing model! Keep up the good work.

**Comment by afollestad** [comment]
I'll look into this, thank you!

**Comment by afollestad** [comment]
@t0phr it's actually working great for me.

It appears it's an issue specific to your phone or Android version. Not sure what can really be done about it at the moment.

Any ideas? @plusCubed 

![screen shot 2015-02-25 at 12 55 05 pm](https://cloud.githubusercontent.com/assets/1820165/6377967/9b6fff78-bced-11e4-8533-a70ca5af1796.png)

**Comment by t0phr** [comment]
I did a little more research, logcat tells me this:

W/System.err(11518): 4: 
W/System.err(11518): 	at com.jcraft.jsch.ChannelSftp._stat(Unknown Source)
W/System.err(11518): 	at com.jcraft.jsch.ChannelSftp._stat(Unknown Source)
W/System.err(11518): 	at com.jcraft.jsch.ChannelSftp.ls(Unknown Source)
W/System.err(11518): 	at com.jcraft.jsch.ChannelSftp.ls(Unknown Source)
W/System.err(11518): 	at com.afollestad.cabinet.sftp.SftpClient.lsSync(Unknown Source)
W/System.err(11518): 	at com.afollestad.cabinet.sftp.SftpClient$6.run(Unknown Source)
W/System.err(11518): 	at java.lang.Thread.run(Thread.java:818)
W/System.err(11518): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=32768; regionStart=0; regionLength=1107121384
W/System.err(11518): 	at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
W/System.err(11518): 	at java.io.PipedInputStream.read(PipedInputStream.java:283)
W/System.err(11518): 	at com.jcraft.jsch.ChannelSftp.fill(Unknown Source)
W/System.err(11518): 	at com.jcraft.jsch.ChannelSftp.fill(Unknown Source)
W/System.err(11518): 	... 7 more
W/System.err(11518): 4: 
W/System.err(11518): 	at com.jcraft.jsch.ChannelSftp.ls(Unknown Source)
W/System.err(11518): 	at com.jcraft.jsch.ChannelSftp.ls(Unknown Source)
W/System.err(11518): 	at com.afollestad.cabinet.sftp.SftpClient.lsSync(Unknown Source)
W/System.err(11518): 	at com.afollestad.cabinet.sftp.SftpClient$6.run(Unknown Source)
W/System.err(11518): 	at java.lang.Thread.run(Thread.java:818)
W/System.err(11518): Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=32768 srcPos=4 dst.length=262144 dstPos=0 length=262144
W/System.err(11518): 	at java.lang.System.arraycopy(Native Method)
W/System.err(11518): 	at com.jcraft.jsch.Buffer.getByte(Unknown Source)
W/System.err(11518): 	at com.jcraft.jsch.Buffer.getString(Unknown Source)
W/System.err(11518): 	... 5 more

I'm not sure if this helps. I've seen more enlightening traces..

**Comment by t0phr** [comment]
And I found a better workaround: changing display orientation.
When I do this, the folder's content is displayed correctly. This is what logcat tells me when phone is rotated: http://pastebin.com/F1QXiffH

**Comment by plusCubed** [comment]
@afollestad Found [this](http://stackoverflow.com/questions/28411153/jsch-suppressed-java-lang-classnotfoundexception-lorg-ietf-jgss-oid) stackoverflow post for that Fabric.io issue, but there's no answer right now. I think, as you said, it's a device thing (for that crash at least). @t0phr said the app didn't crash though.

**Comment by afollestad** [comment]
Well, it looks like these issues are mostly related to the SFTP library being used (Jsch).

Not sure if anything can be done until it gets updated.

**Comment by afollestad** [comment]
@t0phr does this still happen in the latest versions?

**Comment by t0phr** [comment]
Nope, it's working great, thanks for fixing it!
On Apr 9, 2015 10:04 PM, Aidan Follestad <notifications@github.com> wrote:@t0phr does this still happen in the latest versions?

**Comment by pilophae** [comment]
This still doesn't work for me. My SSH-server advertises gssapi-with-mic support, which needs the `org.ietf.jgss` classes, which aren't bundled in Dalvik. Maybe https://github.com/cconlon/kerberos-java-gssapi could work as a replacement?

**Comment by afollestad** [comment]
Hmm, I don't think that would quite help much. We don't deal with low level API stuff like that in our current code.

**Comment by afollestad** [comment]
This should be fixed in the new update, hopefully, since Jsch got an update. Let me know if that's not the case.

**Comment by pilophae** [comment]
Still the same crash, unfortunately. Jsch still uses the same classes.

**Comment by xmarteo** [comment]
@afollestad On my Nexus 5 with Android 5.1 and Cabinet 1.9.3.1, SFTP listing is working fine, as well as file moving, but file opening within SFTP loops indefinitely on a "Connecting..." overlay. Is that simply obviously a Jsch thing or should I submit an issue?

**Comment by afollestad** [comment]
Closing this in favor of another issue.

**Comment by afollestad** [comment]
Replaced with https://github.com/afollestad/cabinet-issue-tracker/issues/180

**Comment by afollestad** [comment]
Again, make sure you see that new issue for further details. You can subscribe to it to get notified of any changes.

However, I may've found a solution, let me know if the crashes stop in the next update. If you're not in the beta channel, make sure you are: https://plus.google.com/+AidanFollestad/posts/gFLYYWVvvSD
