### ISSUE TITLE
When rename a file: Superuser not available

### ISSUE THREAD

**Issue by mussab1** [afollestad/cabinet-issue-tracker#277]
Whenever I rename a file, the file witg the new name goes to the end of the list, with "Super user not available" written under it.

If I go out of the

**Comment by plusCubed** [comment]
Renaming should be fixed.

**Comment by andry888** [comment]
I found this bug in the latest build of v1.8.0.1. The problem persist when moving files too. My phone runs unrooted Android 4.4

**Comment by andry888** [comment]
I found similar issue: #311

**Comment by Geyup** [comment]
I see this issue in Samsung Galaxy S3 using Cabinet 1.9.8.1

I tried renaming in several areas, sdcard and internal memory, no good, can't rename anything!

Ahhh this sucks, please fix... :(

![rename](https://cloud.githubusercontent.com/assets/13072581/14134396/832eb902-f646-11e5-9370-f6c7e33799ed.jpg)

**Comment by andry888** [comment]
The simplest quick fix would be to refer back to version 1.9.7. Sure you lose some feature but at least it will become more functional.

**Comment by Geyup** [comment]
I'll wait for an update...

thanks
